version: "3.8"

services:
  kumiho:
    image: ghcr.io/hichamll04/kumiho:latest
    container_name: kumiho
    ports:
      - "9999:9999"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./books:/books
    environment:
      - TZ=Asia/Seoul
      - PORT=9999
      - PLUGIN_SECRET_KEY=${PLUGIN_SECRET_KEY:-1234}
      - PLUGIN_REGISTRY_URL=https://raw.githubusercontent.com/kumiho-plugin/kumiho-plugin-registry/main/index.json
    restart: unless-stopped
